### ISSUE TITLE
Extension of the current web framework

### ISSUE THREAD

**Issue by allinorcannon** [mateugazi/czasteczkowa-inzynierka#10]

**Comment by mateugazi** [comment]
Add in the default view the option to select on of the following modes:

1. Train a new model
2. Fine tune one of the already existing models.
3. Get a predictions from existing models.

Additionally, implement part of the features from third path:

1. Allow user to upload csv and send a request to the server.
2. Create a server that will be able to read the file, convert it to form that is suitable for exemplary model and get a prediction from that model.
3. Send a response with predictions and display it in the form of the table on the web
